os: linux
sudo: required
dist: trusty

language: generic

before_install:
    - mkdir ~/swift
    - sudo apt-get install clang libicu-dev
    - curl -O https://swift.org/builds/swift-3.0-release/ubuntu1404/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu14.04.tar.gz
    - tar xzf swift-3.0-RELEASE-ubuntu14.04.tar.gz -C ~/swift
    - echo 'export PATH=~/swift/swift-3.0-RELEASE-ubuntu14.04/usr/bin:"${PATH}"' >> ~/.bashrc
    - source ~/.bashrc

script: swift test
